spring:
  application:
    name: gcp
  datasource:
#    url: jdbc:mysql://localhost:3306/gcpdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    url: jdbc:mysql:///gcpdb?cloudSqlInstance=senac-hello-world-475422:us-central1:mysql-gcp&socketFactory=com.google.cloud.sql.mysql.SocketFactory&ipTypes=PUBLIC&useSSL=false&serverTimezone=America/Sao_Paulo
    username: ${DB_USER:sa}
#    password: password
    password: ${sm://DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # para dev: create, create-drop, update; em prod use migrations
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.H2Dialect    # No H2
        dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
#senac-hello-world
