spring:
  application:
    name: gcp
  datasource:
#    url: jdbc:mysql://localhost:3306/gcpdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    url: jdbc:mysql://p701046739643-60ib3s@gcp-sa-cloud-sql.iam.gserviceaccount.com:3306/gcpdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update   # para dev: create, create-drop, update; em prod use migrations
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.H2Dialect    # No H2
        dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
#senac-hello-world